version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: auth0extensions/ci-node:generic
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker-compose build
      - run:
          name: Archive Docker image
          command: docker save $(docker images -q) -o images.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./images.tar

  publish-latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/images.tar
      # - run:
      #     name: Publish Docker Image to Docker Hub
      #     command: |
      #       echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      #       docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
